#!/bin/bash

 case_dir=/work2/noaa/gsienkf/weihuang/jedi/case_study

 run_dir=run_80.40t1n_36p
 output=1

#caselist=(amsua iasi)
 caselist=(amsua iasi)

 for i in ${!caselist[@]}
 do
   gridfile=regrid/${caselist[$i]}
   if [ ! -f ${gridfile} ]
   then
     cd regrid
     rm -f fv3latlon.nc
    #interp.sh ${case_dir}/sfc-letkf/analysis/increment/
     interp.sh ${case_dir}/${caselist[$i]}/${run_dir}/analysis/increment/
     cd ..
     mv regrid/fv3latlon.nc ${gridfile}
   fi

   if [ "${caselist[$i]}" == "iasi" ]
   then
     obsfile=${case_dir}/${caselist[$i]}/manmade-iasi-obs/iasi_metop-a_obs_2020121500_m.nc4
   else
     obsfile=${case_dir}/${caselist[$i]}/manmade-amsua-obs/amsua_n19_obs_2020121500_m.nc4
   fi

   if [ -f ${obsfile} ]
   then
     python new-obs-jedi.py \
       --output=${output} \
       --casename=${caselist[$i]} \
       --varname=T \
       --gridfile=${gridfile} \
       --obsfile=${obsfile}
   fi
 done

 exit 0

 caselist=(aircraft sfcship sondes)
#var_list=(tsen   tv     uv     q)
 var_list=(tsen)

 for i in ${!caselist[@]}
 do
   gridfile=regrid/${caselist[$i]}
   if [ ! -f ${gridfile} ]
   then
     cd regrid
     rm -f fv3latlon.nc
    #interp.sh ${case_dir}/sfc-letkf/analysis/increment/
     interp.sh ${case_dir}/${caselist[$i]}/${run_dir}/analysis/increment/
     cd ..
     mv regrid/fv3latlon.nc ${gridfile}
   fi

   for j in ${!var_list[@]}
   do
     echo "i = $i, j = $j"
     obsfile=${case_dir}/${caselist[$i]}/ioda_v2_data/${caselist[$i]}_${var_list[$j]}_obs_2020011006.nc4
     if [ -f ${obsfile} ]
     then
       python new-obs-jedi.py \
         --output=${output} \
         --casename=${caselist[$i]}_${var_list[$j]} \
         --varname=T \
         --gridfile=${gridfile} \
         --obsfile=${obsfile}
     fi
   done
 done

 caselist=(satwind scatwind vadwind windprof)
 var_list=(uv)

 run_dir=run_80.40t1n_36p
 output=1

 for i in ${!caselist[@]}
 do
   gridfile=regrid/${caselist[$i]}
   if [ ! -f ${gridfile} ]
   then
     cd regrid
     rm -f fv3latlon.nc
    #interp.sh ${case_dir}/sfc-letkf/analysis/increment/
     interp.sh ${case_dir}/${caselist[$i]}/${run_dir}/analysis/increment/
     cd ..
     mv regrid/fv3latlon.nc ${gridfile}
   fi

   for j in ${!var_list[@]}
   do
     echo "i = $i, j = $j"
     obsfile=${case_dir}/${caselist[$i]}/ioda_v2_data/${caselist[$i]}_obs_2020011006.nc4
     if [ -f ${obsfile} ]
     then
       python new-obs-jedi.py \
         --output=${output} \
         --casename=${caselist[$i]}_${var_list[$j]} \
         --varname=T \
         --gridfile=${gridfile} \
         --obsfile=${obsfile}
     fi
   done
 done

