#!/bin/bash

 set -x

#workdir=/work2/noaa/gsienkf/weihuang/jedi/case_study/develop_code
#workdir=/work2/noaa/gsienkf/weihuang/jedi/case_study
#caselist=(amsua iasi aircraft sfcship sondes surf satwind scatwind vadwind windprof)
#caselist=(iasi aircraft sondes scatwind)
 workdir=/work2/noaa/gsienkf/weihuang/jedi/per_core_timing/run
#caselist=(halo_aircraft)
#caselist=(anna_roundRobin_aircraft)
#caselist=(anna_halo_aircraft anna_roundRobin_aircraft halo_aircraft roundRobin_aircraft)
#caselist=(anna_halo_aircraft_2 anna_roundRobin_aircraft_2)
#caselist=(solver_halo_aircraft)
 caselist=(solver_RoundRobin_aircraft)

 for i in ${!caselist[@]}
 do
   rm -rf ${caselist[$i]}
   mkdir -p ${caselist[$i]}
   python parallel-observer-stats-profiling.py \
	--casename=${caselist[$i]} \
	--workdir=${workdir} \
	--output=1
 done

#python make-jedi-perf-panel.py --output=1

