#!/bin/bash

 set -x

#workdir=/work2/noaa/gsienkf/weihuang/jedi/case_study/develop_code
 workdir=/work2/noaa/gsienkf/weihuang/jedi/case_study
#caselist=(amsua iasi aircraft sfcship sondes surf satwind scatwind vadwind windprof)
 caselist=(iasi aircraft sondes scatwind)

 for i in ${!caselist[@]}
 do
   rm -rf ${caselist[$i]}
   mkdir -p ${caselist[$i]}
   python parallel-stats-profiling.py --casename=${caselist[$i]} --workdir=${workdir} --output=1
 done

 python make-jedi-perf-panel.py --output=1

