#!/bin/bash

 set -x

 workdir=/work2/noaa/gsienkf/weihuang/jedi/run
 caselist=(halo_maxpoolsize_1 halo_maxpoolsize_tpe rr_maxpoolsize_1 rr_maxpoolsize_tpe)

 for i in ${!caselist[@]}
 do
   rm -rf ${caselist[$i]}
   mkdir -p ${caselist[$i]}
   python parallel-observer-stats-profiling.py \
	--casename=${caselist[$i]} \
	--workdir=${workdir} \
	--output=1
 done

