#!/bin/bash

 set -x

#caselist=(amsua iasi aircraft sfcship sondes surf satwind scatwind vadwind windprof)
 caselist=(amsua iasi aircraft sondes satwind scatwind)

 for i in ${!caselist[@]}
 do
   python main_timing.py --casename=${caselist[$i]}
  #python obs_timing.py --casename=${caselist[$i]}
   python sum_timing.py --casename=${caselist[$i]}
 done

